package main.java.model;

public enum DataItems {
    NAME,
    AGE,
    ADDRESS,
    EMAIL,
    GPS_LOCATION,
    OCCUPATION,
    ETHNICITY,
    RELIGION,
    MARITAL_STATUS,
    CREDIT_CARD_NUMBER,
    MEDICINE_CURRENTLY_TAKEN,
    PREVAILING_HEALTH_CONDITIONS,
    FAMILY_HEALTH_CONDITIONS,
    WEIGHT,
    HEIGHT,
    PHOTOGRAPH,
    BIRTHDAY,
    MONTHLY_INCOME,
    GENDER,
    FAVOURITE_FOOD,
    ALLERGIES,
    ANNUAL_INCOME,
    INSURANCE

}
