package main.java.model;

public enum DataItems {
    NAME,
    AGE,
    ADDRESS,
    EMAIL,
    LOCATION,
    OCCUPATION,
    ETHNICITY,
    RELIGION,
    MARITAL_STATUS,
    CREDIT,
    MEDICINE_CURRENTLY_TAKEN,
    PREVAILING_HEALTH_CONDITIONS,
    WEIGHT,
    HEIGHT,
    PHOTOGRAPH,
    BIRTHDAY,
    MONTHLY_INCOME,
    GENDER,
    FAVOURITE_FOOD

}
